const ITEM_TYPES = [
    // Hairbrushes
    { id: 'brush_pink', name: 'Pink Hairbrush', color: '#FFB6C1' },
    { id: 'brush_gold', name: 'Golden Hairbrush', color: '#FFD700' },
    { id: 'brush_purple', name: 'Purple Hairbrush', color: '#DA70D6' },
    { id: 'brush_silver', name: 'Silver Hairbrush', color: '#C0C0C0' },
    { id: 'brush_rose', name: 'Rosewood Brush', color: '#8B4513' },
    // Stuffed Animals
    { id: 'toy_bear', name: 'Teddy Bear', color: '#A0522D' },
    { id: 'toy_unicorn', name: 'Unicorn Plush', color: '#FFF0F5' },
    { id: 'toy_bunny', name: 'Pink Bunny', color: '#FFC0CB' },
    { id: 'toy_dragon', name: 'Purple Dragon', color: '#9400D3' },
    { id: 'toy_cat', name: 'Calico Cat Plush', color: '#F4A460' },
    { id: 'toy_elephant', name: 'Gray Elephant', color: '#708090' },
    { id: 'toy_dog', name: 'Puppy Plush', color: '#D2B48C' },
    { id: 'toy_panda', name: 'Panda Plush', color: '#2F4F4F' },
    { id: 'toy_owl', name: 'Wise Owl Plush', color: '#556B2F' },
    { id: 'toy_lion', name: 'Lion Cub Plush', color: '#FFA500' },
    // Perfume Bottles
    { id: 'perfume_round', name: 'Round Perfume', color: '#E6E6FA' },
    { id: 'perfume_tall', name: 'Tall Perfume', color: '#F08080' },
    { id: 'perfume_blue', name: 'Blue Essence', color: '#ADD8E6' },
    { id: 'perfume_star', name: 'Star Bottle', color: '#FFFFE0' },
    { id: 'perfume_heart', name: 'Heart Perfume', color: '#FF69B4' },
    { id: 'perfume_green', name: 'Emerald Mist', color: '#50C878' },
    { id: 'perfume_black', name: 'Midnight Scent', color: '#1a1a1a' },
    { id: 'perfume_orange', name: 'Citrus Bloom', color: '#FF8C00' },
    { id: 'perfume_teal', name: 'Ocean Breeze', color: '#008080' },
    { id: 'perfume_red', name: 'Rose Petal', color: '#DC143C' },
    // Jewelry
    { id: 'jewel_ring_ruby', name: 'Ruby Ring', color: '#E0115F' },
    { id: 'jewel_ring_diam', name: 'Diamond Ring', color: '#E0FFFF' },
    { id: 'jewel_neck_gold', name: 'Gold Necklace', color: '#DAA520' },
    { id: 'jewel_neck_pearl', name: 'Pearl Necklace', color: '#F5F5F5' },
    { id: 'jewel_ear_blue', name: 'Sapphire Earrings', color: '#0000FF' },
    { id: 'jewel_ear_pink', name: 'Pink Diamond Earrings', color: '#FFB6C1' },
    { id: 'jewel_bracelet', name: 'Charm Bracelet', color: '#B8860B' },
    { id: 'jewel_tiara', name: 'Mini Tiara', color: '#F0F8FF' },
    { id: 'jewel_brooch', name: 'Butterfly Brooch', color: '#9932CC' },
    { id: 'jewel_anklet', name: 'Silver Anklet', color: '#778899' },
    // Clothing/Accessories
    { id: 'acc_ribbon_red', name: 'Red Ribbon', color: '#FF0000' },
    { id: 'acc_ribbon_blue', name: 'Blue Ribbon', color: '#0000CD' },
    { id: 'acc_glove_white', name: 'Silk Glove', color: '#FFFFFF' },
    { id: 'acc_fan', name: 'Lace Fan', color: '#FFF5EE' },
    { id: 'acc_mirror', name: 'Hand Mirror', color: '#4682B4' },
    { id: 'acc_comb', name: 'Ivory Comb', color: '#FFFFF0' },
    { id: 'acc_slipper', name: 'Glass Slipper', color: '#B0E0E6' },
    { id: 'acc_crown', name: 'Princess Crown', color: '#FFD700' },
    { id: 'acc_wand', name: 'Magic Wand', color: '#FAFAD2' },
    { id: 'acc_purse', name: 'Beaded Purse', color: '#D8BFD8' },
    // Books/Letters
    { id: 'book_red', name: 'Fairytale Book', color: '#B22222' },
    { id: 'book_blue', name: 'Poetry Book', color: '#4169E1' },
    { id: 'book_green', name: 'Garden Journal', color: '#228B22' },
    { id: 'letter_sealed', name: 'Sealed Letter', color: '#FDF5E6' },
    { id: 'scroll', name: 'Old Scroll', color: '#DEB887' },
    // Tea Set
    { id: 'tea_cup', name: 'Tea Cup', color: '#FFFAF0' },
    { id: 'tea_saucer', name: 'Saucer', color: '#FFFAF0' },
    { id: 'tea_pot', name: 'Tea Pot', color: '#F0FFF0' },
    { id: 'tea_spoon', name: 'Silver Spoon', color: '#DCDCDC' },
    { id: 'tea_sugar', name: 'Sugar Bowl', color: '#F5FFFA' },
    // Flowers
    { id: 'flower_rose', name: 'Single Rose', color: '#FF0000' },
    { id: 'flower_lily', name: 'White Lily', color: '#FFFFFF' },
    { id: 'flower_tulip', name: 'Pink Tulip', color: '#FF69B4' },
    { id: 'flower_daisy', name: 'Daisy', color: '#FFFF00' },
    { id: 'flower_violet', name: 'Violet', color: '#8A2BE2' },
    // Miscellaneous
    { id: 'misc_candle', name: 'Scented Candle', color: '#FFE4E1' },
    { id: 'misc_key', name: 'Golden Key', color: '#FFD700' },
    { id: 'misc_box', name: 'Music Box', color: '#CD853F' },
    { id: 'misc_shell', name: 'Sea Shell', color: '#FFF5EE' },
    { id: 'misc_feather', name: 'Peacock Feather', color: '#008080' },
    { id: 'misc_ball', name: 'Glass Ball', color: '#AFEEEE' },
    { id: 'misc_clock', name: 'Pocket Watch', color: '#DAA520' },
    { id: 'misc_vial', name: 'Magic Potion', color: '#FF00FF' },
    { id: 'misc_statue', name: 'Glass Swan', color: '#F0FFFF' },
    { id: 'misc_cushion', name: 'Silk Cushion', color: '#DC143C' },
    { id: 'misc_mask', name: 'Masquerade Mask', color: '#4B0082' },
    { id: 'misc_quill', name: 'Quill Pen', color: '#708090' },
    { id: 'misc_ink', name: 'Ink Well', color: '#000080' },
    { id: 'misc_comb2', name: 'Silver Comb', color: '#C0C0C0' },
    { id: 'misc_mirror2', name: 'Compact Mirror', color: '#FFC0CB' }
];
