const ITEM_TYPES = [
    // Hairbrushes
    { id: 'brush_pink', name: 'Pink Hairbrush', icon: 'mdi:hairbrush', color: '#FFB6C1' },
    { id: 'brush_gold', name: 'Golden Hairbrush', icon: 'mdi:hairbrush', color: '#FFD700' },
    { id: 'brush_purple', name: 'Purple Hairbrush', icon: 'mdi:hairbrush', color: '#DA70D6' },
    { id: 'brush_silver', name: 'Silver Hairbrush', icon: 'ph:brush-duotone', color: '#C0C0C0' },
    { id: 'brush_rose', name: 'Rosewood Brush', icon: 'ph:brush-fill', color: '#8B4513' },
    // Stuffed Animals
    { id: 'toy_bear', name: 'Teddy Bear', icon: 'ph:teddy-bear-fill', color: '#A0522D' },
    { id: 'toy_unicorn', name: 'Unicorn Plush', icon: 'mdi:unicorn', color: '#FFF0F5' },
    { id: 'toy_bunny', name: 'Pink Bunny', icon: 'ph:rabbit-fill', color: '#FFC0CB' },
    { id: 'toy_dragon', name: 'Purple Dragon', icon: 'mdi:dragon', color: '#9400D3' },
    { id: 'toy_cat', name: 'Calico Cat Plush', icon: 'ph:cat-fill', color: '#F4A460' },
    { id: 'toy_elephant', name: 'Gray Elephant', icon: 'mdi:elephant', color: '#708090' },
    { id: 'toy_dog', name: 'Puppy Plush', icon: 'ph:dog-fill', color: '#D2B48C' },
    { id: 'toy_panda', name: 'Panda Plush', icon: 'mdi:panda', color: '#2F4F4F' },
    { id: 'toy_owl', name: 'Wise Owl Plush', icon: 'mdi:owl', color: '#556B2F' },
    { id: 'toy_lion', name: 'Lion Cub Plush', icon: 'mdi:emoticon-cool', color: '#FFA500' },
    // Perfume Bottles
    { id: 'perfume_round', name: 'Round Perfume', icon: 'mdi:bottle-tonic-plus', color: '#E6E6FA' },
    { id: 'perfume_tall', name: 'Tall Perfume', icon: 'mdi:bottle-tonic', color: '#F08080' },
    { id: 'perfume_blue', name: 'Blue Essence', icon: 'ph:flask-fill', color: '#ADD8E6' },
    { id: 'perfume_star', name: 'Star Bottle', icon: 'mdi:star-circle', color: '#FFFFE0' },
    { id: 'perfume_heart', name: 'Heart Perfume', icon: 'mdi:heart-box', color: '#FF69B4' },
    { id: 'perfume_green', name: 'Emerald Mist', icon: 'ph:drop-fill', color: '#50C878' },
    { id: 'perfume_black', name: 'Midnight Scent', icon: 'mdi:bottle-wine', color: '#1a1a1a' },
    { id: 'perfume_orange', name: 'Citrus Bloom', icon: 'ph:orange-fill', color: '#FF8C00' },
    { id: 'perfume_teal', name: 'Ocean Breeze', icon: 'ph:waves-fill', color: '#008080' },
    { id: 'perfume_red', name: 'Rose Petal', icon: 'mdi:bottle-tonic-outline', color: '#DC143C' },
    // Jewelry
    { id: 'jewel_ring_ruby', name: 'Ruby Ring', icon: 'mdi:ring', color: '#E0115F' },
    { id: 'jewel_ring_diam', name: 'Diamond Ring', icon: 'ph:sketch-logo-fill', color: '#E0FFFF' },
    { id: 'jewel_neck_gold', name: 'Gold Necklace', icon: 'mdi:necklace', color: '#DAA520' },
    { id: 'jewel_neck_pearl', name: 'Pearl Necklace', icon: 'ph:dots-three-circle-vertical-fill', color: '#F5F5F5' },
    { id: 'jewel_ear_blue', name: 'Sapphire Earrings', icon: 'mdi:gender-female', color: '#0000FF' },
    { id: 'jewel_ear_pink', name: 'Pink Diamond Earrings', icon: 'ph:star-four-fill', color: '#FFB6C1' },
    { id: 'jewel_bracelet', name: 'Charm Bracelet', icon: 'mdi:watch', color: '#B8860B' },
    { id: 'jewel_tiara', name: 'Mini Tiara', icon: 'mdi:crown', color: '#F0F8FF' },
    { id: 'jewel_brooch', name: 'Butterfly Brooch', icon: 'mdi:butterfly', color: '#9932CC' },
    { id: 'jewel_anklet', name: 'Silver Anklet', icon: 'ph:link-simple-horizontal-bold', color: '#778899' },
    // Clothing/Accessories
    { id: 'acc_ribbon_red', name: 'Red Ribbon', icon: 'mdi:ribbon', color: '#FF0000' },
    { id: 'acc_ribbon_blue', name: 'Blue Ribbon', icon: 'ph:bookmarks-fill', color: '#0000CD' },
    { id: 'acc_glove_white', name: 'Silk Glove', icon: 'mdi:hand-back-right', color: '#FFFFFF' },
    { id: 'acc_fan', name: 'Lace Fan', icon: 'ph:wind-fill', color: '#FFF5EE' },
    { id: 'acc_mirror', name: 'Hand Mirror', icon: 'mdi:mirror', color: '#4682B4' },
    { id: 'acc_comb', name: 'Ivory Comb', icon: 'ph:list-dashes-fill', color: '#FFFFF0' },
    { id: 'acc_slipper', name: 'Glass Slipper', icon: 'mdi:shoe-heel', color: '#B0E0E6' },
    { id: 'acc_crown', name: 'Princess Crown', icon: 'ph:crown-fill', color: '#FFD700' },
    { id: 'acc_wand', name: 'Magic Wand', icon: 'mdi:auto-fix', color: '#FAFAD2' },
    { id: 'acc_purse', name: 'Beaded Purse', icon: 'mdi:purse', color: '#D8BFD8' },
    // Books/Letters
    { id: 'book_red', name: 'Fairytale Book', icon: 'mdi:book-open-variant', color: '#B22222' },
    { id: 'book_blue', name: 'Poetry Book', icon: 'mdi:book-alphabet', color: '#4169E1' },
    { id: 'book_green', name: 'Garden Journal', icon: 'mdi:book-leaf', color: '#228B22' },
    { id: 'letter_sealed', name: 'Sealed Letter', icon: 'mdi:email-seal', color: '#FDF5E6' },
    { id: 'scroll', name: 'Old Scroll', icon: 'mdi:scroll', color: '#DEB887' },
    // Tea Set
    { id: 'tea_cup', name: 'Tea Cup', icon: 'mdi:cup', color: '#FFFAF0' },
    { id: 'tea_saucer', name: 'Saucer', icon: 'mdi:circle-outline', color: '#FFFAF0' },
    { id: 'tea_pot', name: 'Tea Pot', icon: 'mdi:teapot', color: '#F0FFF0' },
    { id: 'tea_spoon', name: 'Silver Spoon', icon: 'mdi:spoon-sugar', color: '#DCDCDC' },
    { id: 'tea_sugar', name: 'Sugar Bowl', icon: 'mdi:shaker', color: '#F5FFFA' },
    // Flowers
    { id: 'flower_rose', name: 'Single Rose', icon: 'mdi:flower-tulip', color: '#FF0000' },
    { id: 'flower_lily', name: 'White Lily', icon: 'mdi:flower', color: '#FFFFFF' },
    { id: 'flower_tulip', name: 'Pink Tulip', icon: 'ph:flower-lotus-fill', color: '#FF69B4' },
    { id: 'flower_daisy', name: 'Daisy', icon: 'ph:flower-fill', color: '#FFFF00' },
    { id: 'flower_violet', name: 'Violet', icon: 'ph:flower-tulip-fill', color: '#8A2BE2' },
    // Miscellaneous
    { id: 'misc_candle', name: 'Scented Candle', icon: 'mdi:candle', color: '#FFE4E1' },
    { id: 'misc_key', name: 'Golden Key', icon: 'mdi:key-variant', color: '#FFD700' },
    { id: 'misc_box', name: 'Music Box', icon: 'mdi:archive', color: '#CD853F' },
    { id: 'misc_shell', name: 'Sea Shell', icon: 'mdi:shell', color: '#FFF5EE' },
    { id: 'misc_feather', name: 'Peacock Feather', icon: 'ph:feather-fill', color: '#008080' },
    { id: 'misc_ball', name: 'Glass Ball', icon: 'mdi:crystal-ball', color: '#AFEEEE' },
    { id: 'misc_clock', name: 'Pocket Watch', icon: 'mdi:clock-outline', color: '#DAA520' },
    { id: 'misc_vial', name: 'Magic Potion', icon: 'ph:flask-bold', color: '#FF00FF' },
    { id: 'misc_statue', name: 'Glass Swan', icon: 'mdi:bird', color: '#F0FFFF' },
    { id: 'misc_cushion', name: 'Silk Cushion', icon: 'ph:square-fill', color: '#DC143C' },
    { id: 'misc_mask', name: 'Masquerade Mask', icon: 'mdi:drama-masks', color: '#4B0082' },
    { id: 'misc_quill', name: 'Quill Pen', icon: 'mdi:feather', color: '#708090' },
    { id: 'misc_ink', name: 'Ink Well', icon: 'mdi:invert-colors', color: '#000080' },
    { id: 'misc_comb2', name: 'Silver Comb', icon: 'ph:list-fill', color: '#C0C0C0' },
    { id: 'misc_mirror2', name: 'Compact Mirror', icon: 'ph:circle-fill', color: '#FFC0CB' }
];
